extends: airbnb-base
env:
  node: true
rules:
  strict: 0
  global-require: 0
  no-multi-spaces:
    - error
    - exceptions:
        VariableDeclarator: true
  import/no-extraneous-dependencies: 0
  no-unused-vars:
    - error
    - argsIgnorePattern: "next"
  no-param-reassign:
    - error
    - props: false
  no-console: 0
  arrow-body-style: 0
  no-debugger: 0
  no-plusplus: 0
  no-restricted-syntax: 0
  no-prototype-builtins: 0
  key-spacing: 0
  max-len: 0
